distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Jul 24 10:06:52 2018"
installation_id: "f4b08b1d-732e-4079-883a-d25b588adffc"
rime_version: 1.2.9