distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Sat Mar 10 22:21:43 2018"
installation_id: "b5786f59-fddc-422b-8a2e-0647a237d5e1"
rime_version: 1.2.9